### ISSUE TITLE
Build site on travis

### ISSUE THREAD

**Issue by davydovanton** [hanami/hanami.github.io#132]
Hello,
I think that it'll be very helpful. Because it'll allow automatically update the site.

Related link:
https://iamstarkov.com/deploy-gh-pages-from-travis/

/cc @hanami/core-team

**Comment by joneslee85** [comment]
Done

**Comment by davydovanton** [comment]
Amazing! :star2:

**Comment by jodosha** [comment]
@joneslee85 Thank you very much. It was always on my list. Awesome :sparkles: :100: :sparkles:

**Comment by AlfonsoUceda** [comment]
:tophat:

**Comment by iamstarkov** [comment]
glad to see that my article can help you

**Comment by joneslee85** [comment]
@iamstarkov thanks for the article
