### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by envygeeks** [hanami/hanami.github.io#138]
I was wondering what the license of your source is, more specifically the design and it's assets.

**Comment by joneslee85** [comment]
Regarding the code side, I am sure it is MIT. But I am unsure about design and assets. We might consider CC for it, with one exception with the trademark logo.

**Comment by jodosha** [comment]
Hey, sorry for missing this information. The contents are [CC by-nc-sa 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/), while the name and logo TM.

Of course I will grant permissions to anyone wants to print stickers or put the logo on the website or whatever fair usage.

**Comment by joneslee85** [comment]
@envygeeks I hope this answer your question. Would you be able to create PR with Licensing details for README? TIA
