### ISSUE TITLE
Various issues with 'Getting started' guide

### ISSUE THREAD

**Issue by tragiclifestories** [hanami/hanami.github.io#158]
I've been going through the guide and I've hit several places where it seems to be out of date or otherwise wrong.

* `hanami new bookshelf --database=postgres` will generate a project which uses minitest, not rspec, but all the code examples use rspec
* the rspec examples use the old `foo.should.match bar` syntax, which nowadays is [not recommended](https://github.com/rspec/rspec-expectations/blob/master/Should.md). Some of the test examples just don't run at all (those that use `must_equal` and co; there is also one random `assert`, which of course also fails in an rspec context)

I can try to fix some of these issues, although I would need some guidance as to whether to change the test examples to minitest (since that is the out-of-the-box default), or change them to `expect` syntax, or whatever.

**Comment by joneslee85** [comment]
@tragiclifestories thanks for filing this issue. I agree that the Getting Started Guide should be more consistent regarding the test framework choice. IMO I would opt for minitest instead of RSpec because of its being bundled with Ruby.

**Comment by tragiclifestories** [comment]
Yes, especially as that's what `hanami new` gives you without further specification. I personally prefer the RSpec-style assertions, but at the end of the day it's all just different ways to throw an error if something is false.

**Comment by cllns** [comment]
Thanks for submitting this @tragiclifestories! 

The Getting Started guide actually is using Minitest :smile:

It's just using the ['spec' syntax](http://www.rubyinside.com/a-minitestspec-tutorial-elegant-spec-style-testing-that-comes-with-ruby-5354.html), rather than the normal syntax.

**Comment by tragiclifestories** [comment]
D'oh! And that's how long it's been since I used minitest ...

**Comment by joneslee85** [comment]
I vote for spec style minitest for every test examples in Getting Started guide. Should we do it?

cc @AlfonsoUceda @jodosha

**Comment by cllns** [comment]
@joneslee85 The only ones I see that use `assert` are feature specs, but it looks like we'd need to add [`capybara_minitest_spec`](https://github.com/ordinaryzelig/capybara_minitest_spec) to change those over.

**Comment by jodosha** [comment]
@tragiclifestories No worries about the confusion. We're happy that you opened this ticket anyway. Sync guides with actual implementation is hard. Better to check from time to time. :wink: 

@joneslee85 @cllns The "Getting Started" guide targets the most possible "vanilla" version of a Hanami project. Moving to RSpec like syntax for MiniTest or `capybara_minitest_spec`, requires that people following the guide to install these extra gems.
