### ISSUE TITLE
Weird-feeling phrase in `hanami.github.io/source/guides/views/testing.md`

### ISSUE THREAD

**Issue by TPei** [hanami/hanami.github.io#172]
> We can both understand if a specific presentational logic behaves correctly and/or assert if the rendered markup.

I feel like a) there's something missing at the end ("assert if the rendered markup is correct") or b) the sentence should be slightly different ("assert the contents of the rendered markup").

**Comment by TPei** [comment]
See #173 and #174 for proposed changes

**Comment by jodosha** [comment]
Closed by #173
