### ISSUE TITLE
Inconsistency in Getting Started – “there isn't an else condition”, but there is

### ISSUE THREAD

**Issue by roryokane** [hanami/hanami.github.io#207]
The [Getting Started guide](http://hanamirb.org/guides/getting-started/) has a confusing inconsistency here:

> With our validations in place, we can limit our entity creation and redirection to cases where the incoming params are valid:
> 
> ```ruby
> # apps/web/controllers/books/create.rb
> module Web::Controllers::Books
>   class Create
>     include Web::Action
> 
>     expose :book
> 
>     params do
>       required(:book).schema do
>         required(:title).filled(:str?)
>         required(:author).filled(:str?)
>       end
>     end
> 
>     def call(params)
>       if params.valid?
>         @book = BookRepository.create(Book.new(params[:book]))
> 
>         redirect_to '/books'
>       else
>         self.status = 422
>       end
>     end
>   end
> end
> ```
> 
> You may have noticed that there isn't an `else` condition to that `if` statement.
> What happens when params aren't valid?

The paragraph after the code says that there isn’t an `else` condition, but there is one – it says `self.status = 422`. There is no other nearby code block that the paragraph could be referring to.

When I look at the [history] of [`getting-started.md`][getting-started.md], I see that commit 4f5f0712fb333f5427245c3b7821ce22578c008b “Guides: explain the differences between #halt and #status=” created this inconsistency. That commit mainly edited the HTTP Status section of the [Action Control Flow](http://hanamirb.org/guides/actions/control-flow/) page, but edited two code blocks in Getting Started too. The `else` condition was added without the following paragraph being updated.

[history]: https://github.com/hanami/hanami.github.io/commits/9270574ea31df7fd28d4c7398b3635a6a4ccbce6/source/guides/getting-started.md
[getting-started.md]: https://github.com/hanami/hanami.github.io/blob/9270574ea31df7fd28d4c7398b3635a6a4ccbce6/source/guides/getting-started.md

I don’t know enough to suggest whether the `else` condition should be removed or the paragraph after the code should be revised.

**Comment by cllns** [comment]
Thanks for submitting this @roryokane. This is a great find. Often when editing code in documentation, it's easy to mess up the context around it.

I just opened #209 to fix this. Let me know what you think on that PR please :)

**Comment by roryokane** [comment]
@cllns Sorry I didn’t provide feedback earlier. I think your change fixes the problem just fine.

**Comment by cllns** [comment]
No worries, thanks for opening it!
