### ISSUE TITLE
Separate guides into respective repos

### ISSUE THREAD

**Issue by cllns** [hanami/hanami.github.io#213]
Hi there,

I have an idea for restructuring the guides into their own respective repos. 

For example, rather than having the `assets` guides in this repo (`hanami/hanami.github.io`) at `source/guides/assets/`, we could put the guides *inside* the `hanami/assets` repo, at `guides/`

Then the build tool here could just clone each of the repos and build the site based on that. Travis could listen to each repo for commits and rebuild the site for every one, to ensure it's up-to-date.

Here's the current `sources/guides` folder, and where they'd be relocated to (`/guides` in each repo unless specified):

```
actions/              => hanami/controller
architectures/        => hanami/hanami (guides/architectures)
command-line/         => hanami/hanami (guides/command-line)
helpers/              => hanami/helpers
mailers/              => hanami/mailer
models/               => hanami/model  (guides/)
upgrade-notes/        => hanami/hanami (guides/upgrade-notes) - or stays here
applications/         => hanami/hanami (guides/applications)
assets/               => hanami/assets
getting-started.md    => hanami/hanami (or stays here)
index.md              => stays here
migrations/           => hanami/model (guides/migrations)
routing/              => hanami/router
views/                => hanami/view
```

This would fix the issue of having to make two separate PR's for changes that affect the guides. Though you'd still have to do that for changes that affect the `getting-started` guide. The blog would stay in this repo.

This would also help people searching for something in, let's say, `hanami/controller` that is answered in the guide for that section.

Thoughts? 
@hanami/core-team  @hanami/contributors

**Comment by jodosha** [comment]
@cllns Thanks for the suggestion but Guides are only for full stack Hanami projects.

Putting Guides in single repositories can be confusing because single gems can be used as standalone components in other Ruby projects.

This would also increase the complexity of maintaining guides, deploy and contributing to them. Would a person require to clone all the Hanami repositories to fix a typo in the Guides?

My vote is 👎

**Comment by davydovanton** [comment]
I'm agree with @jodosha 👍

**Comment by cllns** [comment]
Thanks for the quick response and explaining your reasoning. That makes sense! 👍

**Comment by cllns** [comment]
[A new GitHub feature](https://github.com/blog/2228-simpler-github-pages-publishing) announced yesterday would make this approach slightly more attractive IMO, but not enough to reopen this issue. Just wanted to record it here for reference.
