### ISSUE TITLE
Interactor Guide

### ISSUE THREAD

**Issue by cllns** [hanami/hanami.github.io#215]
`Hanami::Interactor`, in [`hanami/utils`](https://github.com/hanami/utils) is a very useful component.

We should consider adding a Guide to the website about how to use it (and the benefits of it).

Perhaps it could be an extension of the `Getting Started` guide, working from the `bookshelf` example.

There's no `Hanami::Utils` section on the site, so not sure if that's worth adding.

Happy to help write/review this guide, if we choose to move forward with it.

**Comment by vladdypwnz** [comment]
I'm on it, captn

**Comment by joneslee85** [comment]
@cllns I agree, we should have a guide on that. Feel free to proceed.
@vladdypwnz please work with @cllns to ensure you two do not step on each other's foot. thanks for your offer 👍

**Comment by vladdypwnz** [comment]
@joneslee85 Hey I have a pretty good draft I think. I'm new to helping out on github. How do I best submit it?

**Comment by cllns** [comment]
Fork this repo, then add your draft, commit it (preferably to a branch for your sake, but `master` works too), and push it up. Then open a PR against this repo (and reference this issue, #215, in it)

**Comment by cllns** [comment]
Closed via #299
