### ISSUE TITLE
Make better navigation menu for mobile site

### ISSUE THREAD

**Issue by AlfonsoUceda** [hanami/hanami.github.io#226]
Hi folks:

I open this issue because when you navigate the guides from a mobile it's a little irritating when you click a link and then you have to scroll down again.

You can see a screenshot to see what is the first thing you see when enter in the guides:

![fireshot capture 6 - hanami i guides - getting started - http___hanamirb org_guides_getting-started_](https://cloud.githubusercontent.com/assets/925961/20248171/1f42cb12-a9de-11e6-8f63-cc807e9cc2c7.png)

I think we could have a select instead the list, what do you think?

**Comment by AlfonsoUceda** [comment]
Do you like something like this simple css or we need to add navigation arrows?

![fireshot capture 7 - hanami i guides - gettin_ - http___macbookpro local_4567_guides_getting-started](https://cloud.githubusercontent.com/assets/925961/20248418/128c0220-a9e4-11e6-9d6b-fc193e6dfa36.png)

**Comment by AlfonsoUceda** [comment]
cc @hanami/core-team @hanami/contributors

**Comment by cllns** [comment]
👍 

I'd also be into moving the navigation to the left (for wide screens), if you're messing around in the CSS :D There's no reason to have it on the right, and it's pretty unusual IMO

**Comment by AlfonsoUceda** [comment]
@cllns Yes, to me it's a little weird to me but maybe I prefer use another issue for that.

**Comment by davydovanton** [comment]
@AlfonsoUceda looks awesome 👍

**Comment by beauby** [comment]
@AlfonsoUceda :+1:

**Comment by TiteiKo** [comment]
👍

**Comment by jodosha** [comment]
Closed by #227
