### ISSUE TITLE
Getting Started - Remove Postgres in favor of SQLite

### ISSUE THREAD

**Issue by cllns** [hanami/hanami.github.io#236]
```
hanami new bookshelf --database=postgres
```
should just be
```
hanami new bookshelf
```

We don't use any advanced features of Postgres, and it makes the Getting Started guide more complicated. Some users may have to spend time installing Postgres (which can be a pain!) or dealing with authentication issues... all just to learn the basics of Hanami! 

I think we should include a note telling users that we're using SQLite and that in a production app they should use Postgres or some other production-ready database (and show them it's easy to use postgres instead: `hanami new bookshelf --database=postgres`)

**Comment by jodosha** [comment]
I found people that were confused if their PG server was down, or which configuration file to edit in case they wanted to add credentials to the connection string. This happened both in chat and during a workshop.

By replacing PG with SQLite, we remove these problems as there isn't a server to start or credential to ad..
