### ISSUE TITLE
Need fix on the getting started guide - working with entities

### ISSUE THREAD

**Issue by pongsanti** [hanami/hanami.github.io#239]
As from the section of the getting started page [working-with-entities](http://hanamirb.org/guides/getting-started/#working-with-entities)
> For now, we want it to carry title and author information. Let's add these attributes.
>
>`# lib/bookshelf/entities/book.rb`
>`class Book < Hanami::Entity`
>`end`

The text implies that readers should add attributes which I suppose is not true.

**Comment by davydovanton** [comment]
good catch 👍 
fixed in https://github.com/hanami/hanami.github.io/pull/240

**Comment by AlfonsoUceda** [comment]
closed by #240
