### ISSUE TITLE
Need verification on a portion of the architectures page

### ISSUE THREAD

**Issue by pongsanti** [hanami/hanami.github.io#242]
As from the [Architectures](http://hanamirb.org/guides/architecture/overview/#application-core) page, there is a sentence said that
>Indeed, by opening lib/bookshelf.rb, we find the Bookshelf module, which is the main namespace of our project.

From my workspace, I don't see `Module Bookshelf` on such file. My lib/bookshelf.rb content is as follow
`Hanami::Utils.require!("#{__dir__}/bookshelf")`

Not sure if such text is still valid.

**Comment by AlfonsoUceda** [comment]
@pongsanti You are right, this is an outdated sentence, can you make a PR for removing that? thanks!

**Comment by pongsanti** [comment]
fixed in #244 
Please help verify

**Comment by AlfonsoUceda** [comment]
fixed by https://github.com/hanami/hanami.github.io/pull/244
