### ISSUE TITLE
Be more specific about mounting applications

### ISSUE THREAD

**Issue by beauby** [hanami/hanami.github.io#245]
The [guides](http://hanamirb.org/guides/routing/overview/#mounting-applications) simply say:
> If we want to mount an application, we should use mount.

It would be helpful to specify that the `mount` instruction should go to `config/environment.rb`.

**Comment by cllns** [comment]
Is `config/environment.rb` the right place? I'd think `mount` would belong in `config/routes.rb`

**Comment by beauby** [comment]
@cllns `$ hanami generate app foo` adds a `mount` instruction within `config/environment.rb`. There is no stock `config/routes.rb` in the root directory (at least when using `$ hanami new`).

**Comment by cllns** [comment]
ah, of course :)

**Comment by jodosha** [comment]
@beauby Hi, yes we should specify how to mount an application. Would you like to contribute to solve poor documented feature? Thanks. 😄

**Comment by spaceghoul** [comment]
I've attempted to address this with #261 please let me know if it needs rewording
