### ISSUE TITLE
Method in views (confusing example)

### ISSUE THREAD

**Issue by sovetnik** [hanami/hanami.github.io#266]
Given [example](https://github.com/hanami/hanami.github.io/blob/build/source/guides/helpers/forms.md#method-in-views) maybe should be replaced by another one, not bound to form, because passing wrong params cause error
```  1) Error:
Add a book#test_0002_displays list of errors when params contains errors:
NameError: undefined local variable or method `form' for #<Hanami::View::Rendering::Scope:0x007fe0fa942e00>
Did you mean?  fork
```
Error happens because template is rendering from _Web::Views::Books::Create_ instead _Web::Views::Books::New_ and Create view don't have _form_ method

And this may be confusing, especially when passing tutorial in first time.

**Comment by davydovanton** [comment]
@sovetnik hey, are you sure that your link is right? I don't see any problems in this form (https://github.com/hanami/hanami.github.io/blob/build/source/guides/helpers/forms.md#method-in-views) method

**Comment by davydovanton** [comment]
@sovetnik any updates? :)

**Comment by sovetnik** [comment]
No ;)

**Comment by AlfonsoUceda** [comment]
Closing this issue, it seems stale.
