### ISSUE TITLE
[WIP][Community Translation] Russian translation

### ISSUE THREAD

**Issue by gbezyuk** [hanami/hanami.github.io#268]
Just started at https://github.com/translation-gang/ru.hanami.github.io
Primary maintainer is @sovetnik.

**Comment by davydovanton** [comment]
Hey @gbezyuk, thanks for the idea. I think it will be better to create something like http://rusrails.ru instead fork of the main site. What do you think?

**Comment by gbezyuk** [comment]
@davydovanton, well, we at @translation-gang focus on simple translation of documentation. We have nothing against going beyond that, but our primary goal and responsibility is just simple as that.

**Comment by sovetnik** [comment]
@davydovanton standalone site is good idea.

**Comment by gbezyuk** [comment]
What we work on IS a standalone website, isn't it?

**Comment by davydovanton** [comment]
@gbezyuk yep, but we can make it easier. I think I can help with translation and site 👍

**Comment by gbezyuk** [comment]
Feel free to join. Although, I don't get what you mean by making it easier. The purpose of the fork is to keep translation in sync with the original, anyway,

**Comment by AlfonsoUceda** [comment]
Hi folks thanks for the issue, but as @davydovanton said, translations should be done in another site. I mean, fork the site, translate English to Russian and then host in the place you want.

This is because we can't afford translate all languages so it's better people maintain our own fork.

**Comment by gbezyuk** [comment]
@AlfonsoUceda we'll do. All we ask is to keep this issue open and maybe inform people via a link in your README so if anybody else would want to translate it into Russian he or she'll see that the work  is already in progress.

**Comment by davydovanton** [comment]
@gbezyuk I can add link to awesome hanami site ;)

**Comment by gbezyuk** [comment]
Better than nothing, yet doesn't help with the above mentioned issue.
