### ISSUE TITLE
'Download, Develop, Deploy in 5 minutes.' section doesn't work because heroku doesn't support sqlite

### ISSUE THREAD

**Issue by bbonislawski** [hanami/hanami.github.io#269]
Some time ago `sqlite` was set to be default adapter. After that deploy on heroku doesn't work(since heroku doesn't support sqlite). Instruction should be updated to don't confuse newcomers which would see that it doesn't work

**Comment by AlfonsoUceda** [comment]
@bbonislawski thanks for the issue ;)

**Comment by AlfonsoUceda** [comment]
closed by #270
