### ISSUE TITLE
Anchor icon

### ISSUE THREAD

**Issue by eko24ive** [hanami/hanami.github.io#277]
Hello,
Anchor icon which is used on the blog posts is differs from the site styleguide (IMHO) 
![image](https://cloud.githubusercontent.com/assets/25591824/23019118/71cc7c2e-f449-11e6-8244-6456aa5dbab2.png)

May I submit PR for it, or this works as designed ?

**Comment by davydovanton** [comment]
hey @eko24ive. If you submit PR it will be awesome 👍

**Comment by eko24ive** [comment]
Ok !

**Comment by AlfonsoUceda** [comment]
@eko24ive some progress on this?

**Comment by eko24ive** [comment]
Holy molly.
Sorry @AlfonsoUceda totally forgot about it somehow. Although I creater PR - please review it https://github.com/hanami/hanami.github.io/pull/305

**Comment by eko24ive** [comment]
Besides `git clone git@github.com:hanami/hanami.github.io.git` command from README fails with this message:
```
$ git clone git@github.com:hanami/hanami.github.io.git
Cloning into 'hanami.github.io'...
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
ERROR: Your account is suspended. Please contact support@github.com for more information.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I was able to pull it using github generated link from text input at the top though.
So I guess README have to be updated, do you want another PR 😄  ?

**Comment by davydovanton** [comment]
okay, I checked anchors and all works correctly
![screenshot 2017-07-30 02 33 42](https://user-images.githubusercontent.com/1147484/28749430-b4e95d68-74cf-11e7-9156-99db5ac48a54.jpeg)
![screenshot 2017-07-30 02 34 09](https://user-images.githubusercontent.com/1147484/28749431-b515abac-74cf-11e7-9815-8dad2b5b87d9.jpeg)

**Comment by eko24ive** [comment]
@davydovanton any updates regarding README guide of cloning repo ?

**Comment by davydovanton** [comment]
@eko24ive nope. All works from box :)
