### ISSUE TITLE
Update community page

### ISSUE THREAD

**Issue by davydovanton** [hanami/hanami.github.io#301]
I checked new crystal site design and found that they have excellent community page:
https://crystal-lang.org/community/

I think we can create something similar for hanami too. WDYT?
/cc @hanami/core

**Comment by jodosha** [comment]
@davydovanton I like it. What @hanami/community folks think?

**Comment by artofhuman** [comment]
Good idea 👍

**Comment by marionschleifer** [comment]
@davydovanton I think this would be a great idea 👍 How do we go about this? 
@jodosha Should we discuss the content in our next 1on1 and then I'll set it up?

**Comment by davydovanton** [comment]
@marionschleifer I can create simple prototype for this page and after that you'll update all texts. WDYT? :)

**Comment by marionschleifer** [comment]
@davydovanton That would be perfect :)

**Comment by AlfonsoUceda** [comment]
@davydovanton great idea ;)

**Comment by davydovanton** [comment]
closed by #307
