### ISSUE TITLE
Remove bundle directory

### ISSUE THREAD

**Issue by radar** [hanami/hanami.github.io#314]
The `bundle` directory is quite large and takes a long time to clone down here in Kangaland. I would suggest removing this directory and instead relying on the `Gemfile.lock`. 

My concern with it being so huge is that it is a barrier-to-entry for new OSS contributors, who may also come from countries with slow internet connections.

WDYT?

**Comment by b264** [comment]
I also notice it has darwin extensions in it and not everyone is running their POSIX on darwin

**Comment by tudorpavel** [comment]
@radar, my thoughts exactly. Surely the `bundle` directory doesn't need to be inside the repo.

From the #140 PR it seems to me it was a solution for the Travis [build failure](https://travis-ci.org/hanami/hanami.github.io/builds/105964885) when building the sitemap.

**Comment by graywolf** [comment]
I don't understand the request. Even if the dir is deleted (which it was in #389 ), it's still part of repo history and therefore downloaded when cloning. Unless I'm missing something fundamental about git here.

We could rewrite histore and remove it complete but not sure it that's worth it.

**Comment by radar** [comment]
If you removed it now then a shallow clone would be fast. As I said in OP, it would significantly lower the bar to entry.

**Comment by radar** [comment]
With it deleted in the other issue, then this fixes my issue.
