### ISSUE TITLE
Use common style for Command line commands

### ISSUE THREAD

**Issue by alvir** [hanami/hanami.github.io#329]
Examples:
Without `bundle exec` 
`hanami generate action web dashboard#index`
http://hanamirb.org/guides/actions/overview/

With and without lead percent
http://hanamirb.org/guides/projects/rake/

I suppose bundle exec is excess. With rbenv and one version of hanami it works properly without bundle exec. OhMyZsh with some simple settings adds bundle exec to rake commands automatically.

Perhaps these guides are not responsible with bundler and it needs to be moved to Command Line section.

**Comment by b264** [comment]
This is related to https://github.com/hanami/hanami/issues/676

**Comment by cllns** [comment]
@alvir Please read the issue @b264 referenced.

In cases where someone has more than one version of `hanami` installed, they'd have problems. I think we'd rather be explicit, with `bundle exec` and avoid those issues. It's a necessary part of working with ruby (or adding a shell plugin to do it for you), so it's not much of an additional pain. If someone is not used to Ruby, I could see it being annoying, but I think that's a problem with Ruby & not Hanami specifically :D 

We talked about adding `binstubs` to `hanami/hanami`, but haven't made any progress on that. That would switch `bundle exec hanami` for `bin/hanami` in the guides. I don't particularly think that's necessary, but if you want to open an issue in `hanami/hanami` doing that, we can discuss it further.

Closing this issue. Thanks for opening it! We always want to hear feedback like this, even when we choose to go against it. 🌸

**Comment by alvir** [comment]
I mean we need to use common way in docs with bundle exec or without it. Maybe we should add some NB near these Command line places.
