### ISSUE TITLE
Default focus in the search box for guides

### ISSUE THREAD

**Issue by malin-as** [hanami/hanami.github.io#364]
Hi,

This is really a small issue, and maybe it's by even by design, but I find it really annoying that whenever I open a new page in `/guides`, the focus goes to the search box on top, because I can't scroll with PageUp/PageDown right away. And if I scroll with the mouse, when I click on a link (typically on the right-hand side panel), it does not activate the link but removes the focus from the search box. Then I have to click again. And at least on Firefox, the search box, when it receives the focus, extends too much and pushes the top-right-hand links div down, pushing the whole page contents down, so that means that the link will move up after the first click.

I hope that makes sense.

**Comment by malin-as** [comment]
Sorry, I'm a bootstrap novice and have no idea how to fix it!

**Comment by cllns** [comment]
It looks like we need to remove `autofocus` here: https://github.com/hanami/hanami.github.io/blob/077a3e87c19a56ba3823c6598d6ae164b1399551/source/_navbar.erb#L18

If you're willing and able, you can submit a PR removing that. If not, I can take care of it :cheer

**Comment by AlfonsoUceda** [comment]
Hi folks, I've fixed it https://github.com/hanami/hanami.github.io/commit/0f137e4b5579f55c674020740c6536a7d0f474dc

Thanks for reporting it @malin-as
