### ISSUE TITLE
On responsive site the dropdown always selects Getting Started on any page

### ISSUE THREAD

**Issue by PhilT** [hanami/hanami.github.io#367]
## Steps to reproduce

Reduce the width of your browser until you see the dropdown (or browse to the getting started guide on your phone).

Then select a topic from the dropdown.

## Result

Correct page shows but dropdown still shows 'Getting started'

**Comment by AlfonsoUceda** [comment]
Fixed by https://github.com/hanami/hanami.github.io/pull/374
