### ISSUE TITLE
Syntax highlighting bug

### ISSUE THREAD

**Issue by cllns** [hanami/hanami.github.io#372]
Noticed a bug on [the helpers/escape guide](http://hanamirb.org/guides/helpers/escape/) today:

<img width="792" alt="screen shot 2017-09-10 at 7 34 27 pm" src="https://user-images.githubusercontent.com/632942/30255227-39ab9dda-965f-11e7-94e8-aed6a2045301.png">

@davydovanton any ideas?

**Comment by davydovanton** [comment]
@cllns the problem was in invalid html `img` tag in example. I fixed it, could you check? 😊
