### ISSUE TITLE
Update search to only show newest version

### ISSUE THREAD

**Issue by cllns** [hanami/hanami.github.io#437]
<img width="533" alt="image" src="https://user-images.githubusercontent.com/632942/36080688-f4b600e2-0f50-11e8-8860-8fec93f8bd30.png">

Those are links to:
- `/guides/1.0/actions/rack-integration/`
- `/guides/1.1/actions/rack-integration/`
- `/guides/actions/rack-integration/` (which is same as 1.1 right now)

I think we should just link to the last one. What do others think? @davydovanton @hanami/core

**Comment by AlfonsoUceda** [comment]
@cllns that's a good suggestion, I'd like to know if we can search in the current version you have selected, that would be amazing, don't you think?

**Comment by davydovanton** [comment]
I can try to research it 👍

**Comment by siaw23** [comment]
@cllns @davydovanton I tried to fix it so now search only looks in the folder of the latest version folder. So now trying to search `middleware` shows this instead of the above:

**Comment by mbajur** [comment]
This is resolved by #454
