### ISSUE TITLE
Algolia search

### ISSUE THREAD

**Issue by mbajur** [hanami/hanami.github.io#449]
Hello!

Just as a reminder - i was responsible for creating a search widget at the top of hanami docs. It was working pretty well (i would rate it 6/10 tho) but when guides for various version of hanami came out, search results are not working well anymore.

Each article is displayed like 3 times (once for each hanami version) without any indication about which version it refers to. Apart from that, the overall UX of this widget is pretty bad and was pretty bad since the very beginning. The biggest issue/awkwardness is that, after selecting a result from a dropdown, it's not redirecting user to the specific paragraph / heading of given page but, instead, redirects to the top of page found. That's just bad.

I feel kind of bad for it as i was the author of that widget so i decided to make some research on how to make it all work better and it turned out Algolia search service is a damn good choice. They have a free plan for open source projects that can be seamlessly integrated to any doc site without any additional steps required from deploy point of view - they are periodically scrapping a doc site and generating it's index.

Search widgets works really nice, exactly how they should. Alglia is also widely used everywhere (see the full list here: https://community.algolia.com/docsearch/) and you can see it live, for instance, on middleman website: https://middlemanapp.com/basics/install/. However, probably more hanami-like example would be a Vue.js website: https://vuejs.org

I've contacted them already and it all can be done but i need a green light from hanami contributors if you're even interested :) If so, i'll be more than happy to take care of it.

PS. i'm not an Algolia team member, i'm just a hanami docs user and badly want to make them as friendly as possible :)

***

Related issues: #437 #448

**Comment by siaw23** [comment]
Hi, from what I can see, the search is only meant for guides. In that case we can just hack the JS/CSS for it to work like we want without any addition of extra stuff. Just my thoughts 🙂

**Comment by mbajur** [comment]
As far as i know, algolia search can be extended to not only search the guides but also an API or anything else (if i remember well, some core member was interested in that back when i was implementing the current search widget)

**Comment by apohllo** [comment]
A good search is crucial for UX, so IMHO algolia seems to be a good choice for that feat.

**Comment by mbajur** [comment]
@jodosha yeah, sure, i was just waiting for a green light :) Need to finish my conversation with algolia represantive then.

**Comment by mbajur** [comment]
Algolia is now live on production site!
