### ISSUE TITLE
Google search results are dead

### ISSUE THREAD

**Issue by Morozzzko** [hanami/hanami.github.io#484]
I usually find docs in Google, and those are my top results for: "hanami guide"

<img width="838" alt="default" src="https://user-images.githubusercontent.com/887264/50060274-f5b32980-01a2-11e9-9a4a-c8172a27a8d1.png">

Those links are long dead. Would be nice to have some sort of page that would navigate to the latest guides. WDYT?

**Comment by jodosha** [comment]
@Morozzzko Is https://guides.hanamirb.org what you're looking for?

**Comment by Morozzzko** [comment]
> added the `question` label

No, you completely misunderstood my issue.

I don't have a problem with locating the proper guides page. However, I have a hard time googling things because Google shows a lot of links, most of them are long dead.  I'm not the only one, so the overall user experience is affected. It's extremely annoying

The issue could be resolved by providing redirects, or an empty page that says "Docs have been moved there: guides.hanamirb.org".

The best-case scenario: old pages redirect to a similar pages from `guides.hanamirb.org`

**Comment by jodosha** [comment]
@Morozzzko Please have a look at https://github.com/hanami/hanami.github.io/pull/485. It's deploying as I'm writing.

By visiting `/guides` you'll find a message and an automatic redirect to the new website.
